# Netlify에게 백엔드 함수 폴더 위치를 알려주는 지시어일세
[build]
  functions = "netlify/functions"
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "script-src 'self' 'unsafe-eval' 'unsafe-inline' https://*.google.com; object-src 'none';"
